name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repo
        uses: actions/checkout@v3

      - name: Setup Node.js environment
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install dependencies
        run: npm install
        working-directory: ./api

      - name: Run tests
        run: npm test
        working-directory: ./api/tests

      - name: Build the Docker image
        if: success()
        run: docker build ./api --file ./api/Dockerfile --tag my-image-name:$(date +%s)
